name = "drive"
type = "webpack"
workers_dev = true
account_id = "b87997a496f985b46b927b3f24c61de1"
zone_id = "b04152d2c33ff4653cec1a579be6d42a"
kv_namespaces = [
    {binding = "BUCKET", id = "", preview_id = ""}
]

[env.staging]
name = "drive-staging"
